'use strict';
var path = require('path');
var SUGGEST = require(path.join(__dirname, '..', 'js', 'suggestion-engine.js'));
test('unknown table message produces a table-name suggestion', function () { assertTrue(SUGGEST.buildSuggestions('Table "NOPE" does not exist in the active schema.').some(function (x) { return /Pick Tables/.test(x); })); });
test('unknown column message produces a column-name suggestion', function () { assertTrue(SUGGEST.buildSuggestions('Column "NOPE" does not exist on table "IA_INVOICE" in the active schema.').some(function (x) { return /Pick Columns/.test(x); })); });
test('no relationship message mentions define-relationship option', function () { assertTrue(SUGGEST.buildSuggestions('No relationship was found between "IA_INVOICE" and "ADM_USER_GROUP" in the active schema.').some(function (x) { return /define which columns connect them/.test(x); })); });
test('missing WHERE message points at override checkbox', function () { assertTrue(SUGGEST.buildSuggestions('A WHERE condition is required to identify which records should be updated or deleted.').some(function (x) { return /override checkbox/.test(x); })); });
test('no tables selected message mentions description-driven building', function () { assertTrue(SUGGEST.buildSuggestions('At least one table must be selected (or determined from your description).').some(function (x) { return /Build Query/.test(x); })); });
test('"is one of" empty-values message mentions comma-separated guidance', function () { assertTrue(SUGGEST.buildSuggestions('The "Is one of" / "Is not one of" condition on IA_INVOICE.STATUS needs at least one value.').some(function (x) { return /comma/.test(x); })); });
test('"could not identify any tables" message offers a concrete example and mentions manual selection', function () { assertTrue(SUGGEST.buildSuggestions('Could not identify any tables mentioned in your description.').some(function (x) { return /Tables & Columns/.test(x); })); });
test('unknown/unmatched message falls back to a generic suggestion', function () { var s = SUGGEST.buildSuggestions('Some completely unrecognized error text.'); assertEqual(s.length, 1); });
test('handles empty/undefined message without throwing', function () { assertEqual(SUGGEST.buildSuggestions('').length, 1); assertEqual(SUGGEST.buildSuggestions(undefined).length, 1); });
